### ISSUE TITLE
Native Module (IDTECH_MSR_audio) undefined in root index.js

### ISSUE THREAD

**Issue by ghost** [oncethere/react-native-idtech-msr-audio#1]
Peace Chen,

First off, thank you for your documentation. It was very easy to follow.

After walking through the installation steps, I've run into an error importing IDTECH_MSR_audio into my react native project. Once digging in, I've noticed IDTECH_MSR_audio is undefined in the following code _index.js_ file:

`var IDTECH_MSR_audio = require('react-native').NativeModules.IDTECH_MSR_audio;

module.exports = {
  activate: IDTECH_MSR_audio.activate,
  deactivate: IDTECH_MSR_audio.deactivate,
  swipe: IDTECH_MSR_audio.swipe,
};` 

I double checked that the native files are linked by running `react-native link`.

Do you have an idea as to why IDTECH_MSR_audio might be undefined?

In case it helps, here's a screenshot of the Xcode solution.

<img width="273" alt="xcode solution explorerj" src="https://user-images.githubusercontent.com/35221693/38058121-5b014770-32a7-11e8-9074-fc86623ce245.png">

**Comment by peacechen** [comment]
Check that the static library is linked in the project.  It's under **Build Phases** -> **Link Binary With Libraries**.  `react-native link` should do this automatically, but Xcode has a mind of its own.

<img width="723" alt="idtech" src="https://user-images.githubusercontent.com/6295083/38152075-7dabc928-342b-11e8-8705-1d01f76c148e.png">

**Comment by peacechen** [comment]
Does the example project work for you?  That might help give a clue what's missing.

**Comment by ghost** [comment]
I can see what you mean by Xcode having a mind of it's own...

You were correct in that the Library was not linked. After manually linking it, I am now receiving a Dependency Analysis Error saying the library might include it's own product.

![screen shot 2018-03-31 at 6 02 31 am](https://user-images.githubusercontent.com/35221693/38163084-ba0ddeb4-34b3-11e8-9460-5fe60b90cfc8.png)

The only place on my system I was able find libIDTECH_MSR_audio.a was in the Products folder under the Libraries of my project shown below. When adding it, I used the Add Other... option. 

![screen shot 2018-03-31 at 7 20 42 am](https://user-images.githubusercontent.com/35221693/38163125-1b4ca8f4-34b4-11e8-91c9-e917533fad67.png)


Running the example project, was my initial route, but didn't have any luck there either. I just gave it another go and received the same error which is a Lexical or Preprocessor Issue: React/RCTAnimationType.h file not found. Which seems to be another issue with linking?

Any thoughts?

**Comment by peacechen** [comment]
Make sure you added AVFoundation, AudioToolbox, MediaPlayer frameworks to the project.  
https://github.com/oncethere/react-native-idtech-msr-audio#ios-setup

MPVolumeView is provided by Apple's SDK
https://developer.apple.com/documentation/mediaplayer/mpvolumeview

**Comment by Ligator** [comment]
Hi, I am having the same error:

```
In file included from /[path to my project folder]/node_modules/react-native-idtech-msr-audio/ios/IDTECH_MSR_audio/IdTechUniMag.h:21:
../../react-native/React/Base/RCTConvert.h:11:9: fatal error: 'React/RCTAnimationType.h' file not found
#import <React/RCTAnimationType.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

And I am using React Native 0.61.5

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 942.91 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.61.5
```

I added all frameworks and the Microphone permission.

Have you found any fix for this issue?

<img width="1165" alt="Captura de Pantalla 2020-02-28 a la(s) 3 40 33" src="https://user-images.githubusercontent.com/3155325/75537641-06814100-59dd-11ea-8e74-3dd29842e61e.png">

**Comment by peacechen** [comment]
@Ligator 
Please open a new thread for your issue.  Initial impressions are that your RN libs aren't fully linked.  This library uses `RCTConvert.h`, but doesn't use animations.  It looks like the `RCTConvert` library has a dependency on `RCTAnimationType` which I find a surprising change in RN 0.6x.

https://github.com/facebook/react-native/blob/master/React/Base/RCTConvert.h#L11
